### ISSUE TITLE
Lintyai SASS / SCSS linter

### ISSUE THREAD

**Issue by jochemh** [lexazloy/brackets-lintyai#10]
Hi there , i finaly got everything working on my windows machine ;) nice work with this!
I do have one more question.
Is there anyway to lint SCSS and SASS ? Cause those wil be used more then LESS.

Hope you can help me out !
Best regards!

**Comment by lexazloy** [comment]
Hi! Glad to hear (read :)) it.

Add u own lint its pretty simple. In `config.js` u have section per file type (not ext!). Like for `JS`:
```js
exports.javascript = {};
exports.javascript.cmd = 'node "%s/jshint/bin/jshint"';
exports.javascript.re = function(data){
    var result = [];

    data.split('\n').forEach(function(data){
        var match = /^(.+): line (\d+), col (\d+), /.exec(data);

        match && result.push({
            line: match[2],
            message: data.replace(match[0], '')
        });
    });

    return result;
};
exports.javascript.type = {};
exports.javascript.type.warning = /(Missing\s|Unnecessary\s)/;
exports.javascript.type.notice = /\sbut never used/;
``` 

`cmd` its command for linter.
`re` - linters output regexp rules. Function can return `object` (`{line: num, messsage: str}`) or `array of objects` (if linter show every error, not only first).
`type` (optional) - if u want to colorize result. If `type` regexp true for output `message` then `type` name will be set as `message` class.

Message class its typical CSS class. Colors defined in `main.css` file:
```css
.lintyai-gutter.error {
    background: #cc3333;
}

.lintyai-gutter.warning {
    background: #ff9933;
}

.lintyai-gutter.notice {
    background: #ffcc66;
}
```
U can add u own:
```css
.lintyai-gutter.xoxoxo {
    background: #cc3333;
}
```
And make it `type`:
```js
filetype.type.xoxoxo = /regexp/;
```

So. SASS/SCSS linter looks like this (as linter i choose https://github.com/brigade/scss-lint):
```js
// https://github.com/brigade/scss-lint
exports.scss =
exports.sass = {};
exports.scss.cmd = 'scss-lint';
exports.scss.re = function(data){
    var result = [];
    
    data.split('\n').forEach(function(data){
        var match = /(.+):(\d+) /.exec(data);

        match && result.push({
            line: match[2],
            message: data.replace(match[0], '')
        });
    });

    return result;    
};
exports.scss.type = {};
exports.scss.type.warning = /\[W] /;
```

Put it in `config.js`.

I hope its work. :) Ok. It should. I tested but i have some troubles w/ SASS/SCSS. That sucker hate me or something. :)

P.S. Little bit later ill update repo and plugin.
