### ISSUE TITLE
How to make this work?

### ISSUE THREAD

**Issue by Amosss** [lexazloy/brackets-lintyai#11]
I read about config.js and what needs to be done but to no avail. I removed all lint related extensions except for lintyai

css: no linter available for css
javascript/angular: shows comments from jslint (maybe the default of brackets?)
php: I added the 2 paths to php.exe and C:/<path to codesniffer/scripts/phpcs but I get no linter available for php
json: no linter available for json
html: shows comments from htmllint (maybe the default of brackets?) 

What am I doing wrong?
Thanks

**Comment by lexazloy** [comment]
Yes you need every external linter. Like example, u need PHP exe/binary for Lintyai can check `php` files.

If you want default `css`, `less`, `js` and  `json` linters u need installed `npm` (Node's package manager).

For `html` and `xml` you need xmllint.

But you can use your own linters. Just setup `config.js` and you can use alternative linters or add new.

This may be helpful: https://github.com/lexazloy/brackets-lintyai/issues/7#issuecomment-40415908

**Comment by Amosss** [comment]
I edited my question above, maybe while you already replying it, so here goes:

css: I added csslint and I do see lint warnings, but not as colorful as your screenshot

javascript/angular: shows comments from jslint (maybe the default of brackets?) but not as colorful as your screenshot

php: I added the 2 paths to php.exe and C:/<path to codesniffer/scripts/phpcs but I get no linter available for php

json: I added jsonlint and I do see lint warnings, but not as colorful as your screenshot

html: shows comments from htmllint (maybe the default of brackets?) but not as colorful as your screenshot

**Comment by lexazloy** [comment]
If linter not show u error on left sine line numbers, then its not work or using default or another linters.

For add `css`, `less`, `js` and `json` u need do few things.

0. U need `node` and `npm`.

For Windows:
1. open cmd.exe;
2. write `cd /d %appdata%\Brackets\extensions\user\lintyai\node` and press enter;
3. write `npm install` and press enter.

For *nix and Mac:
1. open terminal;
2. write `cd ~/.config/Brackets/extensions/user/lintyai/node` and press enter;
3. write `npm install` and press enter.

> php: I added the 2 paths to php.exe and C:/<path to codesniffer/scripts/phpcs but I get no linter available for php

Its looks like PHP Code Sniffer. Check this https://github.com/lexazloy/brackets-lintyai/issues/2. Or just uncomment lines 73-90 in `config.js`. Here [part of code for Code Sniffer](https://github.com/lexazloy/brackets-lintyai/blob/master/config.js#L72).

**Comment by Amosss** [comment]
OK, we have a progress. Again I removed ALL lint related extensions except lintyai

css: Do I need lesscss or scss entry? what is the difference between them?

javascript/angular: works

php: why do you think the problem is with the sniffer and not the php? Now I do get php lint errors but at the bottom and not with light bulbs. I un-commented  the php sniffer part.
This is what I have for php:
exports.php.cmd = 'C:/@Downloads/BracketsPortable/PHP/php.exe -l';
This is what I have for sniffer:
exports.php.cmd = 'C:/@Downloads/BracketsPortable/PHP/php.exe "C:/@Downloads/BracketsPortable/PHP/PHP_CodeSniffer-master/scripts/phpcs"';

json: works

html: works

**Comment by lexazloy** [comment]
> css: Do I need lesscss or scss entry?

U need `less`. If u do `npm install` it will install `less`. 

> php: why do you think the problem is with the sniffer and not the php? 

Internal PHP linter and Code Sniffer have difference error warnings. So for each u need difference config settings. Then Lintyai can understand how to parse it.

For internal PHP: u should leave default section. 

For Code Sniffer: u should uncomment new section.

**Comment by Amosss** [comment]
**What is %s in the paths? is there a place to define it?**

I'm sorry, my bad and sorry for being slow on this one. It was another lint extension that I forgot to remove so now I really removed all lints except yours. node and npm are installed.

css: I see lint (csslint though it's not installed, maybe internal) in the bottom pane, so lint is working but not as colorful as your screenshot. command in config.js: exports.css.cmd = 'C:/@Downloads/BracketsPortable/NodeJSPortable/App/NodeJS/node "C:/@Downloads/BracketsPortable/Data/home/AppData/Roaming/Brackets/extensions/user/lintyai/node/node_modules/less/bin/lessc" -l --no-color';

js: I see lint (jslint though it's not installed, maybe internal) in the bottom pane, so lint is working but not as colorful as your screenshot. command in config.js: exports.javascript.cmd = 'C:/@Downloads/BracketsPortable/NodeJSPortable/App/NodeJS/node "C:/@Downloads/BracketsPortable/Data/home/AppData/Roaming/Brackets/extensions/user/lintyai/node/node_modules/jshint/bin/jshint"';

php: At the bottom I see both lint and codesniffer warnings **but with colors as your screenshot I see only lint without code sniffer**. command in config.js: exports.php.cmd = 'C:/@Downloads/BracketsPortable/PHP/php.exe -l'; and exports.php.cmd = 'C:/@Downloads/BracketsPortable/PHP/php.exe "C:/@Downloads/BracketsPortable/PHP/PHP_CodeSniffer-master/scripts/phpcs"';

json: I see lint (jsonlint though it's not installed, maybe internal) in the bottom pane, so lint is working but not as colorful as your screenshot. command in config.js: exports.json.cmd = 'C:/@Downloads/BracketsPortable/NodeJSPortable/App/NodeJS/node "C:/@Downloads/BracketsPortable/Data/home/AppData/Roaming/Brackets/extensions/user/lintyai/node/node_modules/jsonlint/lib/cli.js" -q';

html: I see lint (htmlhint though it's not installed, maybe internal) in the bottom pane, so lint is working but not as colorful as your screenshot. I didn't find xml lint as you wrote above. command in config.js: exports.html.cmd = 'xmllint --noout --debug --html';

**Comment by lexazloy** [comment]
> What is %s in the paths?

Its path to Brackets extension folder. 

> is there a place to define it?

[Here](https://github.com/lexazloy/brackets-lintyai/blob/master/main.js#L153).

> now I really removed all lints except yours

This is wrong. U should move back to original `config.js` and start new.

First: do as i said https://github.com/lexazloy/brackets-lintyai/issues/11#issuecomment-184706622.
Second: dont change anything. :)

Now `css`, `less`, `js` and `json` will work.

If u want add PHP then u can change `cmd` path in config or add path to `php` in ur `PATH` environment variables. 

If u want to use Code Sniffer insted of internal PHP linter then [uncomment this part in config](https://github.com/lexazloy/brackets-lintyai/blob/master/config.js#L73-L90) and change path to Code Sniffer in line `exports.php.cmd = 'php "path/to/PHP_CodeSniffer-1.4.8/scripts/phpcs"';`.

**Comment by Amosss** [comment]
I started everything from scratch.

when running npm install I saw a tree of things and in the end:
npm WARN EPACKAGEJSON compilyai.node@1.0.0 No repository field.
npm WARN EPACKAGEJSON compilyai.node@1.0.0 No license field.

is the above OK?

I'm using portable brackets so how can I know that %s is assigned to the correct location? 
    dir = extUtils.getModulePath(module, 'node/node_modules/');
    cmd = cmd.replace('%s', dir); 

You said don't change anything in config.js for css, js and json to work but I also use portable node so don't I need to add its full path to config.js? also, instead of %s, don't I need to put the full path to your node modules folder?

php and php code sniffer can't work together?
for php I did this: exports.php.cmd = 'C:/@Downloads/BracketsPortable/PHP/php -l'; is it ok?
for codesniffer, I have this: exports.php.cmd = 'php "path/to/PHP_CodeSniffer-1.4.8/scripts/phpcs"'; don't I need to change php to its full location like with regular php and path/to/php_codesniffer.... to its full path? there is phpcs and phpcs.bat, which of them do I need to reference?

what about html? it seems to use xmllint and I didn't see it anywhere

**Comment by lexazloy** [comment]
> is the above OK?

No. Its error.

> I'm using portable brackets so how can I know that %s is assigned to the correct location? 

Should be correct. I will know if linters like `js`, `css`, etc will work.

> don't I need to add its full path to config.js?

Maybe. If node not in `PATH`. Try to add path to node. Replace
`exports.javascript.cmd = 'node "%s/jshint/bin/jshint"';`
to:
exports.javascript.cmd = 'path/to/node "%s/jshint/bin/jshint"';

> instead of %s, don't I need to put the full path to your node modules folder?

I dont know where portable Brackets store extensions. If in default folder, then no, u dont need. But if in own folder, then yes.

> for php I did this: exports.php.cmd = 'C:/@Downloads/BracketsPortable/PHP/php -l'; is it ok?

Right.

> don't I need to change php to its full location like with regular php and path/to/php_codesniffer.... to its full path?

U need if `php.exe` is not in `PATH`.

> there is phpcs and phpcs.bat, which of them do I need to reference?

In Windows `phpcs` and `phpcs.bat` is same. When u run `phpcs` Windows will try to run `phpcs.bat`.

> for php
> for codesniffer

U cant do this. U can use only one.
