### ISSUE TITLE
use only the php linting function

### ISSUE THREAD

**Issue by anandisrocking007** [lexazloy/brackets-lintyai#14]
hello sir i use interactive linter as my default linter for js,html and css but they don't have any php linting i was hoping is there a way to use your linter without activating linting for js,html and css but only for php

**Comment by lexazloy** [comment]
Hi. I did not test linters together, but it should work well.

Just keep only php entry in `config.js`.

```
define(function(require, exports){

////////////////////////////////////////////////////////////////////////////////

// http://php.net/
exports.php = {};
exports.php.cmd = 'php -l';
exports.php.re = function(data){
    var match = /(.+) in (.+) on line (\d+)/.exec(data);

    if (data.indexOf('No syntax errors detected') == -1)
        return {
            line: match[3],
            message: match[1]
        };
};

////////////////////////////////////////////////////////////////////////////////

});
```

**Comment by anandisrocking007** [comment]
So I can delete the rest of the settings apart from PHP or also convert it to comment

And one more thing does this extension require internet or the PHP installed as global variable?

**Comment by lexazloy** [comment]
1. Right.

2. You only need installed PHP. It can be in `PATH` or you can put full path to PHP in `exports.php.cmd`:
```
exports.php.cmd = 'C:/Path/To/PHP/php -l';
```

**Comment by anandisrocking007** [comment]
I am sorry i did not understand are you telling me that to create a file named exports.php.cmd
and add inside it 'C:/Path/To/PHP/php -l';

**Comment by lexazloy** [comment]
No. `exports.php.cmd` is option in `config.js` ([check here](https://github.com/lexazloy/brackets-lintyai/blob/master/config.js#L59)). This option tells to script which linter to run and where it is.

**Comment by anandisrocking007** [comment]
Hi just to know i am using the portable version of brackets in a pendrive so the drive letter changes from time to time so i was wondering can i add the php file in the extension usr folder and then add exports.php.cmd = '../PHP(The folder where php is present)/php -l';

**Comment by lexazloy** [comment]
Lintyai can replace `%s` with path to `node` directory ([like here](https://github.com/lexazloy/brackets-lintyai/blob/master/config.js#L7)):
* `%appdata%/Brackets/extensions/user/lintyai/node/node_modules` (on Windows),
* `~/.config/Brackets/extensions/user/lintyai/node/node_modules` (on *nix).

Something like `exports.php.cmd = '%s/../../../../../../PHP/php -l;'` (PHP in AppData folder, or in ~/.config directory) should work fine.

This is example for default Brackets config directory. You should find your for portable version.
